# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7675bdace55608124160ab7f7b74c30c6e03c0bf2fa0a028b1fba320bb91f141ec9869807dcbb95dda89d546aefce049eee69dd4c0ae47ad3f4a4a26930c9227

test:
  secret_key_base: 44d5cc38d5fa135b88ddc32e2cb287cb2e7c4c27253229d2f41e546279161414226681da453c54fdd8ce8b52a58ec5640ecfeb60fe4aad36027393b5b7d1ec71

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
